[color]
background = 'default'
foreground = '#bcc2ff'

; gradient = 0
gradient = 1
gradient_color_1 = '#0d28c0'
gradient_color_2 = '#bcc2ff'
gradient_color_3 = '#d2d5ff'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#0d28c0'
horizontal_gradient_color_2 = '#bcc2ff'
horizontal_gradient_color_3 = '#d2d5ff'
horizontal_gradient_color_4 = '#bcc2ff'
horizontal_gradient_color_5 = '#0d28c0'


