-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#12131b",
  base01 = "#0d0e16",
  base02 = "#1a1b23",
  base03 = "#454655",
  base04 = "#c5c5d7",
  base05 = "#e3e1ed",
  base06 = "#2f3039",
  base07 = "#383842",

  base08 = "#ef95ff",
  base09 = "#f3aeff",
  base0A = "#bcc2ff",
  base0B = "#bcc2ff",
  base0C = "#71008c",
  base0D = "#0d28c0",
  base0E = "#3a427c",
  base0F = "#8994ff",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#0d28c0',
  fg = '#d2d5ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#e862ff',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8f8fa1',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f3aeff',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bcc2ff',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#384cdc',
})