-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#12140e",
  base01 = "#0d0f09",
  base02 = "#1a1c15",
  base03 = "#45483d",
  base04 = "#c5c8b9",
  base05 = "#e3e3d8",
  base06 = "#2f312a",
  base07 = "#383a32",

  base08 = "#8fc8bf",
  base09 = "#a0d0c9",
  base0A = "#c1caab",
  base0B = "#b5d087",
  base0C = "#1f4e4a",
  base0D = "#384d13",
  base0E = "#414a32",
  base0F = "#aab68c",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#384d13',
  fg = '#d1eca0', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#6db7ac',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8f9285',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a0d0c9',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c1caab',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#4f6629',
})