[color]
background = 'light'
foreground = '#4f6629'

; gradient = 0
gradient = 1
gradient_color_1 = '#d1eca0'
gradient_color_2 = '#4f6629'
gradient_color_3 = '#121f00'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#d1eca0'
horizontal_gradient_color_2 = '#4f6629'
horizontal_gradient_color_3 = '#121f00'
horizontal_gradient_color_4 = '#4f6629'
horizontal_gradient_color_5 = '#d1eca0'


