[color]
background = 'light'
foreground = '#525a92'

; gradient = 0
gradient = 1
gradient_color_1 = '#dfe0ff'
gradient_color_2 = '#525a92'
gradient_color_3 = '#0c154b'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#dfe0ff'
horizontal_gradient_color_2 = '#525a92'
horizontal_gradient_color_3 = '#0c154b'
horizontal_gradient_color_4 = '#525a92'
horizontal_gradient_color_5 = '#dfe0ff'


