-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#fbf8ff",
  base01 = "#ffffff",
  base02 = "#f4f2fe",
  base03 = "#c5c5d7",
  base04 = "#454655",
  base05 = "#1a1b23",
  base06 = "#f1effc",
  base07 = "#fbf8ff",

  base08 = "#390048",
  base09 = "#4e0061",
  base0A = "#525a95",
  base0B = "#00168d",
  base0C = "#71008c",
  base0D = "#0d28c0",
  base0E = "#b5bcff",
  base0F = "#404674",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#0d28c0',
  fg = '#d2d5ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#100015',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#757686',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#4e0061',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#525a95',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#bcc2ff',
})