-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#fff8f6",
  base01 = "#ffffff",
  base02 = "#fff0ee",
  base03 = "#d8c2be",
  base04 = "#534340",
  base05 = "#231918",
  base06 = "#ffedea",
  base07 = "#fff8f6",

  base08 = "#5d4d27",
  base09 = "#6f5c2e",
  base0A = "#775651",
  base0B = "#904b3e",
  base0C = "#fae0a6",
  base0D = "#ffdad4",
  base0E = "#ffdad4",
  base0F = "#59403c",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#ffdad4',
  fg = '#3a0a04', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#392f18',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#857370',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#6f5c2e',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#775651',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#ffb4a6',
})