-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#f9f9ff",
  base01 = "#ffffff",
  base02 = "#f3f3fa",
  base03 = "#c3c6cf",
  base04 = "#43474e",
  base05 = "#191c20",
  base06 = "#f0f0f7",
  base07 = "#f9f9ff",

  base08 = "#604b67",
  base09 = "#6e5676",
  base0A = "#555f71",
  base0B = "#3d5f90",
  base0C = "#f7d8ff",
  base0D = "#d5e3ff",
  base0E = "#d9e3f8",
  base0F = "#3f4754",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#d5e3ff',
  fg = '#001c3b', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#45364a',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#74777f',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#6e5676',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#555f71',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#a6c8ff',
})